### ISSUE TITLE
Undefined BUILD_GAMELIFT_SERVER

### ISSUE THREAD

**Issue by jurjjc** [aws/lumberyard#368]
**Describe the bug**
BUILD_GAMELIFT_SERVER is not defined, when build the multiplayer sample dedicated server.

**Steps to reproduce**
lmbr_waf build_win_x64_vs2017_release_dedicated -p dedicated_server

**Lumberyard version**
Lumberyard v1.17.0.0

**Some details**
https://gamedev.amazon.com/forums/questions/73844/multiplayersample-for-gamelift-lumberyard-117.html

**Comment by Aristo7** [comment]
I've posted a reply on https://gamedev.amazon.com/forums/questions/73844/multiplayersample-for-gamelift-lumberyard-117.html#answer-74141
