### ISSUE TITLE
I cannot create a new Amazon Lumberyard Project

### ISSUE THREAD

**Issue by JennaDoll** [aws/lumberyard#370]
Hello, I'm Jenna and I have been trying to install lumberyard for almost a month. Early Jan I bought a Alienware laptop to develop on lumberyard mobile games. Since then I have installed and wipped my laptop over and over again trying to get lumberyard working correctly. Please see below for my issue. If anyone could help me or at least point me in the right direction. I've followed many different ways, tutorials, online lumberyard instructions, and still I am stuck. Thanks in advance.

**Describe the bug**
I cannot create a new Amazon Lumberyard Project

**Steps to reproduce**
1. Installed the Lumberyard 1.17.0.0 Version of Lumberyard from the Lumberyard website
2. Installed all the required packages. See screenshots below:
3. Launched Project Configurator 1.17.0.0
4. Selected Create New
5. Entered the "Name" and then selected default (I've also tried this with "Empty". Note: at first I received errors at step 2 "Configuring Project" saying that the platform, build-tools, google license SDK was not installed. So I ended up downloading Android Studio then unpackaging those files in the same directory that lumberyard was pointing to. After I did that I was able to complete all 5 steps in creating a project.
See screenshot:
![image](https://user-images.githubusercontent.com/45544465/52451334-59970600-2af3-11e9-92ab-50cdff6a75df.png)
6. After I successfully created the project set it as default and closed out of Project Configurator 
7. I clicked Lumberyard Editor 1.17.0.0 icon on my desktop and launched Lumberyard Editor.
8. I got the following error as seen in the screenshot:
![image](https://user-images.githubusercontent.com/45544465/52451448-e641c400-2af3-11e9-8b45-5705632fd362.png)
9. I clicked ok then got the next error in the following screenshot:
![image](https://user-images.githubusercontent.com/45544465/52451703-f1e1ba80-2af4-11e9-98cf-c4dac196bbee.png)

![image](https://user-images.githubusercontent.com/45544465/52453881-2c9c2080-2afe-11e9-90e0-49c6379a920a.png)

10. I performed the following:
Deleted my temp folder: D:\Amazon\Lumberyard\1.17.0.0\dev
Opened a command window and navigated to  D:\Amazon\Lumberyard\1.17.0.0\dev
Ran lmbr_waf configure
Ran lmbr_waf build_win_x64_vs2017_profile -p all

I got some yellow messages during the build, some white,and some green. 
In the end I had a success message below: 

![image](https://user-images.githubusercontent.com/45544465/52451670-ca8aed80-2af4-11e9-9190-f7a7c71b56cd.png)

11. I tried to go back to Lumberyard editor and launch it and I still got the same messages.

12. I bought an Alienware laptop in jan and I have literally been trying to get lumberyard to work for almost a month. I have wipped my computer and tried to reinstall the software over and over again. If anyone could please help me, I've tried everything and search everywhere for a possible result. I have also followed some other install instructions that had me go into visual studio in order to build but I am still getting the same outcome. Please if anyone could help me or point me in the right direction.

**Expected behavior**
Please provide a concise description of what you expected to happen.
- I am expecting to be able to create a new game then launch it in the editor without errors

**Screenshots/Logs**
Please include any relevant screenshots and log files from your game project directory (e.g., C:\Amazon\lumberyard\1.15.0.0\dev\Cache\YOURPROJECT\pc\user\log). Note that you are posting to a public forum so please remove any sensitive information from your log files such as project name & path, IP address, credentials etc. 

I looked in directory for log for my project (C:\Amazon\lumberyard\1.15.0.0\dev\Cache\YOURPROJECT\pc\user\log) and my directory only has the following folders.

![image](https://user-images.githubusercontent.com/45544465/52452004-3ae63e80-2af6-11e9-8f7e-bea9c741a07e.png)

Screenshots from #2 above. 
![image](https://user-images.githubusercontent.com/45544465/52450974-1daf7100-2af2-11e9-8ce9-2f72ec8d4397.png)
![image](https://user-images.githubusercontent.com/45544465/52451009-3b7cd600-2af2-11e9-837c-9d4cac2448e6.png)
![image](https://user-images.githubusercontent.com/45544465/52451028-49caf200-2af2-11e9-9fd3-2712e82c29f7.png)
![image](https://user-images.githubusercontent.com/45544465/52451051-594a3b00-2af2-11e9-82b5-e9c090d45733.png)

![image](https://user-images.githubusercontent.com/45544465/52451062-61a27600-2af2-11e9-84fc-f55706e2e1ee.png)

![image](https://user-images.githubusercontent.com/45544465/52451089-741caf80-2af2-11e9-83e1-1e31cf346122.png)

**Lumberyard version**
State the version of Lumberyard in which you discovered this bug (e.g., v1.14.0.1 or v1.15.0.0 etc.).
Newest version on Amazons website: Lumberyard 1.17.0.0

**[OPTIONAL] What is your role in game development?**
Are you a game designer, engineer, artist, producer, something else?

designer

**[OPTIONAL] Tell us about your project or studio.**
Briefly tell us about your project or studio.

Wanting to use lumberyard to create android/ IOS mobile games

**Comment by joshbeacham** [comment]
**_Disclaimer: I am not an Amazon employee._**

Hey Jenna,

Sorry for all of the trouble! You've done an excellent job explaining the problem, and the screenshots you've posted are very helpful!


I noticed that in the screenshots you posted, that you've setup your installation for Visual Studio 2017.
![image](https://user-images.githubusercontent.com/1560973/52483968-256b2600-2b83-11e9-8e71-83ecab7307b5.png)


Looking at the console where you built the game/engine/tools with build_win_x64_vs2017_profile -p all you likewise selected a build profile for Visual Studio 2017.
![image](https://user-images.githubusercontent.com/1560973/52484144-9e6a7d80-2b83-11e9-9178-37e7fe51bbe0.png)


In the screenshot you posted of an error message that says there was an error when loading gems, I noticed that the file path for the gem that fails to load contains Bin64vc140, which is the directory for Visual Studio 2015, while the directory for Visual Studio 2017 is Bin64vc141.
![image](https://user-images.githubusercontent.com/1560973/52483798-bee60800-2b82-11e9-84e6-15843e049cd9.png)

I suspect that perhaps the editor you are launching is located in the directory for Visual Studio 2015 builds at D:\Amazon\Lumberyard\1.17.0.0\dev\Bin64vc140\Editor.exe

Can you try / confirm that you get the same error message when launching the editor from the directory for Visual Studio 2017 builds at D:\Amazon\Lumberyard\1.17.0.0\dev\Bin64vc141\Editor.exe

Try that out and see if it fixes your issue.

**Comment by jkingpin** [comment]
_Disclaimer: I work on the Amazon Lumberyard team._

Great description and motivational diligence @JennaDoll and even better catch @joshbeacham.

I've confirmed following your thorough steps that by default the editor shortcut installed to your desktop point to the Bin64vc140 folder which is for Visual Studio 2015 builds. 

Running your editor.exe from your \Bin64vc141 directory should get you up and running @JennaDoll.

**Comment by JennaDoll** [comment]
@jkingpin @joshbeacham  OMG Thank you so much for all your help. You have no idea how much this helps me. Not only have you helped me but now I know how to triage this issue should I see it again. I have one last question, since its related somewhat to this thread.

So I deleted all my created Projects and created a new project and it created with success. A
After creating my new project I went to 

Opened a command window and navigated to D:\Amazon\Lumberyard\1.17.0.0\dev
Ran lmbr_waf configure
Ran lmbr_waf build_win_x64_vs2017_profile -p all.

Now here is the issue when I ran 

"Ran lmbr_waf build_win_x64_vs2017_profile -p all"

and stepped away twice now I come back to the following screens. I've experienced this a lot when I was reinstalling lumberyard, and I just restart my computer and kept on moving. Do you think there is a defect in my computer, or is it something with lumberyards settings. Bear in mind I just got this computer last month. Below is a screenshot of the specs of my computer. (btw when my computer restarted I just skipped the command steps and went to launch the new project and my new project launched with no problems.) whats bothering me is that  I ran "lmbr_waf build_win_x64_vs2017_profile -p all" and I got the blue screens.

![image](https://user-images.githubusercontent.com/45544465/52525151-3fc40300-2c5a-11e9-987c-183163a6b635.png)

![image](https://user-images.githubusercontent.com/45544465/52525190-d85a8300-2c5a-11e9-93ca-07e46fffc892.png)


![image](https://user-images.githubusercontent.com/45544465/52525196-ef997080-2c5a-11e9-9327-0e4e2d003780.png)

**Comment by JennaDoll** [comment]
Update: 
so I added a few gems to my project and then tried to run the editor again and got this error

![image](https://user-images.githubusercontent.com/45544465/52526174-dd72fe80-2c69-11e9-846b-b22400cc0edc.png)

This is because I didn't build the project after adding new gems. So I go to build the project again

I tried running the commands again

lmbr_waf configure
lmbr_waf build_win_x64_vs2017_profile -p all.

And lmbr_waf configure runs successfully and lmbr_waf build_win_x64_vs2017_profile -p all will run and eventually gives me the blue screen of death as in the screenshots above.

Does anyone know why I am not able to run the second command without getting the blue screen of death. I've read somewhere that the watch dog violation is related to drivers, but when I go into my device manager I don't see any drivers having any issues. screenshot below:


![image](https://user-images.githubusercontent.com/45544465/52526225-6be78000-2c6a-11e9-846c-da5545ef0f81.png)

**Comment by AMZN-alexpete** [comment]
Hi @JennaDoll, your computer looks powerful enough to compile without issue.  A couple things you can check are if you are running out of hard disk space.  Generally we recommend having 60GB available on the same disk you are compiling on.  Another thing to check is if you have some antivirus software that might be interfering.  Hope this helps!

**Comment by bmk10** [comment]
OPen E:\Amazon\Lumberyard\1.19.0.0\dev\Solutions\LumberyardSDK_vs15.sln 'Set Start up Project' -> 'Editor' , set All Profile | x64 | Auto for build type up top, and Press '>' or F5, let it build. Once its running, it will tell you the code line number thats causing problems. 


There you should be able to Fix the code yourself for what u are doing. And Also Debug, and Write the code ;)


I ALWays run Editor.exe  in debug mode. I'm making a game.

**Comment by ExQDev** [comment]
The same error, 

```
E:\Amazon\Lumberyard\1.21.2.0\dev>lmbr_waf build_win_x64_vs2017_profile -p all
[WAF] Engine Root: E:\Amazon\Lumberyard\1.21.2.0\dev\
[WAF] Executing 'build_win_x64_vs2017_profile' in 'e:\Amazon\Lumberyard\1.21.2.0\dev\BinTemp\win_x64_vs2017_profile'
[WARN] Missing JDK path from Setup Assistant detected. Target platforms that require java will be disabled. Please re-run Setup Assistant with "Compile For Android" enabled and run the configure command again.
[SETTINGS] msvs_version = 15 (default 14)
[SETTINGS] Target Output folder (win_x64_vs2017/profile): Bin64vc141
[WARNING] Incredibuild disabled by build option
[WARN] Invalid module 'AmazonQtControlGallery' in spec 'all'
[WARN] Invalid module 'LyIdentity_shared' in spec 'all'
[WARN] Invalid module 'LyIdentity_static' in spec 'all'
[WARN] Invalid module 'LyInstallerMetrics' in spec 'all'
[WARN] Invalid module 'LyMetricsConsumer' in spec 'all'
[WARN] Invalid module 'LyMetricsProducer_python' in spec 'all'
[WARN] Invalid module 'LyMetricsProducer_shared' in spec 'all'
[WARN] Invalid module 'LyMetricsProducer_static' in spec 'all'
[WARN] Invalid module 'LyMetricsShared_shared' in spec 'all'
[WARN] Invalid module 'LyMetricsShared_static' in spec 'all'
[WARN] Invalid module 'LyzardGems' in spec 'all'
[WARN] Invalid module 'LyzardEngines' in spec 'all'
[WARN] Invalid module 'LyzardProjects' in spec 'all'
[WARN] Invalid module 'NewsBuilder' in spec 'all'
[WARN] Invalid module 'ToolsCrashUploader' in spec 'all'
[WARN] Module use dependency 'CrashHandler' for target 'CrySystem' refers to an invalid module
[WARN] Module use dependency 'LyIdentity_shared' for target 'EditorLib' refers to an invalid module
[WARN] Module use dependency 'LyMetricsProducer_shared' for target 'EditorLib' refers to an invalid module
[WARN] Module use dependency 'LyMetricsShared_shared' for target 'EditorLib' refers to an invalid module
[WARN] Module use dependency 'ToolsCrashHandler' for target 'EditorLib' refers to an invalid module
[WARN] Module use dependency 'ToolsCrashHandler' for target 'AssetProcessor' refers to an invalid module
[WARN] Module use dependency 'LyIdentity_shared' for target 'MaglevControlPanel' refers to an invalid module
[WARN] Module use dependency 'LyMetricsProducer_shared' for target 'MaglevControlPanel' refers to an invalid module
[WARN] Module use dependency 'LyMetricsShared_shared' for target 'MaglevControlPanel' refers to an invalid module
[WARN] Module use dependency 'LyIdentity_shared' for target 'LuaIDE' refers to an invalid module
[WARN] Module use dependency 'LyMetricsProducer_shared' for target 'LuaIDE' refers to an invalid module
[WARN] Module use dependency 'LyMetricsShared_shared' for target 'LuaIDE' refers to an invalid module
[WARN] Module use dependency 'ToolsCrashHandler' for target 'LuaIDE' refers to an invalid module
[WARN] Module use dependency 'LyIdentity_shared' for target 'Profiler' refers to an invalid module
[WARN] Module use dependency 'LyMetricsProducer_shared' for target 'Profiler' refers to an invalid module
[WARN] Module use dependency 'LyMetricsShared_shared' for target 'Profiler' refers to an invalid module
[WARN] Module use dependency 'LyIdentity_shared' for target 'EMotionFX.Editor' refers to an invalid module
[WARN] Module use dependency 'LyMetricsProducer_shared' for target 'EMotionFX.Editor' refers to an invalid module
[WARN] Module use dependency 'LyMetricsShared_shared' for target 'EMotionFX.Editor' refers to an invalid module
[WARN] Module use dependency 'LyIdentity_shared' for target 'ScriptCanvasEditor' refers to an invalid module
[WARN] Module use dependency 'LyMetricsProducer_shared' for target 'ScriptCanvasEditor' refers to an invalid module
[WARN] Module use dependency 'LyMetricsShared_shared' for target 'ScriptCanvasEditor' refers to an invalid module
[WARN] Module use dependency 'LyIdentity_shared' for target 'ScriptCanvasGem.Editor' refers to an invalid module
[WARN] Module use dependency 'LyMetricsProducer_shared' for target 'ScriptCanvasGem.Editor' refers to an invalid module
[WARN] Module use dependency 'LyMetricsShared_shared' for target 'ScriptCanvasGem.Editor' refers to an invalid module
[WARN] Module use dependency 'LyIdentity_shared' for target 'LmbrCentral.Editor' refers to an invalid module
[WARN] Module use dependency 'LyMetricsProducer_shared' for target 'LmbrCentral.Editor' refers to an invalid module
[WARN] Module use dependency 'LyMetricsShared_shared' for target 'LmbrCentral.Editor' refers to an invalid module
unable to find QT
unable to find QT
Traceback (most recent call last):
  File "E:\Amazon\Lumberyard\1.21.2.0\dev\Tools\build\waf-1.7.13\waflib\Scripting.py", line 226, in waf_entry_point
    run_commands()
  File "E:\Amazon\Lumberyard\1.21.2.0\dev\Tools\build\waf-1.7.13\waflib\Scripting.py", line 342, in run_commands
    ctx = run_command(cmd_name)
  File "E:\Amazon\Lumberyard\1.21.2.0\dev\Tools\build\waf-1.7.13\waflib\Scripting.py", line 319, in run_command
    ctx.execute()
  File ".\Tools\build\waf-1.7.13\lmbrwaflib\msvs.py", line 2056, in override_build_state
    old(ctx)
  File ".\Tools\build\waf-1.7.13\lmbrwaflib\build_configurations.py", line 1493, in execute
    return execute_method(self)
  File "E:\Amazon\Lumberyard\1.21.2.0\dev\Tools\build\waf-1.7.13\waflib\Scripting.py", line 696, in execute
    return execute_method(self)
  File "E:\Amazon\Lumberyard\1.21.2.0\dev\Tools\build\waf-1.7.13\waflib\Build.py", line 254, in execute
    self.execute_build()
  File "E:\Amazon\Lumberyard\1.21.2.0\dev\Tools\build\waf-1.7.13\waflib\Build.py", line 277, in execute_build
    self.compile()
  File "E:\Amazon\Lumberyard\1.21.2.0\dev\Tools\build\waf-1.7.13\waflib\Build.py", line 370, in compile
    self.producer.start()
  File "E:\Amazon\Lumberyard\1.21.2.0\dev\Tools\build\waf-1.7.13\waflib\Runner.py", line 307, in start
    self.refill_task_list()
  File "E:\Amazon\Lumberyard\1.21.2.0\dev\Tools\build\waf-1.7.13\waflib\Runner.py", line 209, in refill_task_list
    self.add_outstanding_tasks(next(self.biter))
  File "E:\Amazon\Lumberyard\1.21.2.0\dev\Tools\build\waf-1.7.13\waflib\Build.py", line 818, in get_build_iterator
    self.post_group()
  File "E:\Amazon\Lumberyard\1.21.2.0\dev\Tools\build\waf-1.7.13\waflib\Build.py", line 789, in post_group
    f()
  File "E:\Amazon\Lumberyard\1.21.2.0\dev\Tools\build\waf-1.7.13\waflib\TaskGen.py", line 218, in post
    v()
  File "Tools\build\waf-1.7.13\lmbrwaflib\cry_utils.py", line 883, in add_compiler_dependency
    if os.path.isabs( self.env['CC'] ):
  File "E:\Amazon\Lumberyard\1.21.2.0\dev\Tools\Python\2.7.12\windows\lib\ntpath.py", line 59, in isabs
    return s != '' and s[:1] in '/\\'
TypeError: 'in <string>' requires string as left operand, not list
```

But I've found that there's no version of Qt for VS2017
![изображение](https://user-images.githubusercontent.com/17617393/68514617-eccdb980-0286-11ea-8da8-5d899b4c3916.png)

I cannot download VS2015, because
![изображение](https://user-images.githubusercontent.com/17617393/68514782-61085d00-0287-11ea-9682-7f6c7d591831.png)

And cannot use neither VS2017 nor VS2019 with it.
Please, add support of the last one or fix Qt version for VS version.

**Comment by joshbeacham** [comment]
@ExQDev This is not the same error. Please open a new issue.

**Comment by AMZN-alexpete** [comment]
@ExQDev, Lumberyard uses the 2015 Qt libraries for VS 2015 and VS 2017.  As @joshbeacham said, please open a new issue.

**Comment by JennaDoll** [comment]
Thanks for your help. Everything is now resolved.
