### ISSUE TITLE
An error occurred while loading gems

### ISSUE THREAD

**Issue by JakenHerman** [aws/lumberyard#372]
**Describe the bug**
I keep getting this error when attempting to run the Lumberyard Editor. This is a fresh install of Lumberyard, fresh (full) install of Visual Studio 2017, and a new project created in Project Configurator using only default gems and project settings. I have navigated to `/dev` and I ran `lmbr_waf configure` as well as `lmbr_waf build_win_x64_vs2017_profile -p game` as well as `lmbr_waf build_win_x64_vs2017_profile -p game_and_engine`, and I am still getting the error. The frustrating part is the Error window I'm getting says:

> To continue, please build the current project before attempting to run Asset Processor again.

Which I clearly have done.

**Steps to reproduce**
- Install Amazon Lumberyard
- Create new Project (with default settings)
- Attempt to open Lumberyard Editor

**Expected behavior**
I expected the Lumberyard editor to open and allow me to begin working on my newly created game project.

**Screenshots/Logs**
[Imgur](https://i.imgur.com/SM68Lp8.png)

**Lumberyard version**
Lumberyard v1.17.0.0

**Comment by JakenHerman** [comment]
I've found the problem. Although the Lumberyard Setup Assistant claims that the Clang SDK is optional, it is definitely required. After installing the Clang SDK, the Editor opens without error. Closing.

**Comment by JakenHerman** [comment]
Editor opened without error **once**, now I continue to get the editor even still. Re-opening. This is very concerning. New users of the software can't even get into the editor without error upon error.

**Comment by joshbeacham** [comment]
**Disclaimer: I am not an Amazon employee.**

JakenHerman, sorry for the issue. Can you confirm that this is not the the same as [this issue](https://github.com/aws/lumberyard/issues/370#issuecomment-461823214) ? Thanks.

**Comment by JakenHerman** [comment]
@joshbeacham Unfortunately it is the same issue. I apologize for the duplicate.

**Comment by JakenHerman** [comment]
@jo
