### ISSUE TITLE
Option to quickly edit attached Lua/C++ scripts

### ISSUE THREAD

**Issue by nxrighthere** [aws/lumberyard#389]
It's quite inconvenient to search every time for a certain script in the Asset Browser. Would like to see an option in the component dropdown menu to quickly edit attached Lua/C++ scripts.

![dropdownmenu](https://user-images.githubusercontent.com/8279330/56082655-c3ee5e80-5e34-11e9-9402-2d38016c9082.png)

**Comment by joshbeacham** [comment]
This already exists for LUA, as described in the introduction chapter for LUA, 

> "click Edit Script ({}) to launch the Lua IDE and make changes to your script"

which you can read here:
https://docs.aws.amazon.com/lumberyard/latest/userguide/lua-scripting-intro-add-script-to-component.html

![image](https://user-images.githubusercontent.com/1560973/56083094-bb733500-5dee-11e9-83f5-3aafd7934054.png)


This does not exist for C++, which is not a scripting language, and requires a explicit compilation step. You cannot make live changes to C++ components.

**Comment by nxrighthere** [comment]
> This already exists for LUA, as described in the introduction chapter for LUA,
Thanks, I didn't noticed that.

> This does not exist for C++, which is not a scripting language, and requires a explicit compilation step. You cannot make live changes to C++ components.

Yes, I'm aware of this, and this is one of the reasons why Lumberyard's usability is where developers leave their effort with the engine. You need to make N time-consuming steps to achieve a certain goal while with similar products in this area you only need to make a few clicks, unfortunately.
