### ISSUE TITLE
ECS utilization

### ISSUE THREAD

**Issue by RomanZhu** [aws/lumberyard#391]
Hi

I got very used to proper Entity-Component-System architecture (separate from DOD). And used a lot of ECS frameworks. As you probably know Unity goes in a ECS way.

What are your plans for it?
Main use-case for me would be to query world for all entities with component A and B, without component C and do something with them.

I know there are EBuses for code organization, but ECS feels more logical and easier to track systems execution order.

**Comment by punhetonildo** [comment]
Hi, from what i know Lumaberyard is already using ECS.

**Comment by Scott-LY** [comment]
Hi @RomanZhu, apologies for the delay. Lumberyard does use a component entity system. I've included links to our documentation on the system below.

Regarding searching for entities based on the components they have and/or do not have.

The Entity Outliner currently supports filtering entities by the components they have. However it does not support filtering by missing components.

![EntityOutlinerComponentSearch](https://user-images.githubusercontent.com/32552662/58599105-9f5b1400-8233-11e9-913a-9d368004028b.PNG)

If you need to perform this filter during a run-time operation there is no direct support for doing so currently. I've entered a feature request to add this support.

Component Entity System Documentation: 
https://docs.aws.amazon.com/lumberyard/latest/userguide/component-intro.html

Let me know if this answers your question.

**Comment by RomanZhu** [comment]
Hi
I am talking about proper ECS where:
- components do not contain any logic
- all logic is inside systems 

For example like this: https://github.com/SanderMertens/flecs

**Comment by Scott-LY** [comment]
Hi @RomanZhu, thank you for the feedback. I've forwarded your link and comments on ECS. Please let me know if there's anything else I can help you with.
