### ISSUE TITLE
WASD movement stops working in the editor

### ISSUE THREAD

**Issue by nxrighthere** [aws/lumberyard#393]
**Describe the bug**
WASD movement stops working in the editor randomly while arrows work fine. Switching focus from Lumberyard window to another or clicking to blank space helps sometimes.

**Steps to reproduce**
Enter/exit play mode and select any object in the Entity Outliner using StarterGame project.

**Lumberyard version**
1.18.0.0

**Comment by RomanZhu** [comment]
I have same problem.

**Comment by AMZN-alexpete** [comment]
Unfortunately, we have not been able to reproduce this issue.  Please create a new issue if this occurs in a more recent version of Lumberyard (1.23+)
