### ISSUE TITLE
How to get mouse cursor, while not leaving the game mode?

### ISSUE THREAD

**Issue by RomanZhu** [aws/lumberyard#396]
While looking at samples I tried to look at entities in Entity Outliner.
But mouse can't leave game view until I exit the game mode by pressing Esc.
![image](https://user-images.githubusercontent.com/12017366/56084183-edf55000-5e37-11e9-8b86-db2a436f7a38.png)

Am I missing something?

**Comment by joshbeacham** [comment]
You are looking at a game entity that is rendering a UI Canvas in game mode. To view and edit the UI Entities in the UI Canvas you need to open the Ui Canvas in the UI Editor. You can use the Preview button in the UI Editor to quickly preview how the UI Canvas will behave in game mode.

https://docs.aws.amazon.com/lumberyard/latest/userguide/ui-editor-intro.html

**Comment by RomanZhu** [comment]
I know how to edit UI.
The problem is mouse can't leave game view, while it's playing.

**Comment by joshbeacham** [comment]
Your stated objective was "I tried to look at entities in Entity Outliner". Given that there is only a single game entity, I assumed that you wanted to look at the UI Entities.

If your objective is to unconstrain the mouse in game mode, then your options are limited. Generally, you can show the mouse by pressing alt-tab. The mouse is usually visible when the console is open, which is opened by pressing ~. You can also look into AzFramework::InputSystemCursorRequests::SetSystemCursorState passing UnconstrainedAndVisible

**Comment by RomanZhu** [comment]
That's just not user friendly to constrain them that way with mouse being visible.

**Comment by joshbeacham** [comment]
I don't work for Amazon. I'm just trying to help you because I thought you wanted help. If you want to complain, I've got better things to spend my weekend on.

**Comment by RomanZhu** [comment]
Sorry I don't want to sound rude, english is not my native.
With opened console I can move mouse outside of game view, but I can't click on things.
I can't add that C++ line, as I don't have any IDE for it.

**Comment by joshbeacham** [comment]
This behavior is how game mode is supposed to work, as the perspective window approximates what a user would see when launching a stand alone executable. When a user launches a game they won't see the editor to be able to interact with it. Why do you need to be in game mode to click on entities in the outliner?

Perhaps the AI/Physics mode might be what you're looking for. Try clicking on this button.


![image](https://user-images.githubusercontent.com/1560973/56085325-17e64c80-5e0f-11e9-8308-0d840a3aef30.png)


If you need an IDE, most people I know that work on C++ for Lumberyard use Visual Studio. You can get a free copy of the community edition from Microsoft. https://visualstudio.microsoft.com/vs/community/

**Comment by RomanZhu** [comment]
That button is disabled once I go into play mode.

The reason why I want to look at entities during play mode is debugging.
For example go to some part of the level, see something is misbehaving, go to outliner, select entity and look at what components it has how properties are setup.

**Comment by raphabigal** [comment]
I don't think this functionality is available in lumberyard right now, the editor doesn't reflect stuff from your game mode

Overall I'd say the workflow is a lot less editor-centric than unity and unreal from which you saw this functionality.

**Comment by RomanZhu** [comment]
Alright, thanks
I saw there is IMGUI gem, which adds ability to look at hierarchy inside game view, but it seems like a hack for me.

Will leave issue open until any lumb's developer will say that is intended or it will be added.

**Comment by Scott-LY** [comment]
Hi @RomanZhu, apologies for the delay. being able to use the mouse cursor outside of the Editor viewport during game mode is currently not-supported. Are you looking to edit entities during gamemode or just to look at their components and properties?

**Comment by RomanZhu** [comment]
Edit them too

**Comment by Scott-LY** [comment]
Hi @RomanZhu, thanks for the feedback. I've passed on the request to view and edit these values in Editor Game Mode. Please let me know if there's anything else I can help you with.
