### ISSUE TITLE
Install

### ISSUE THREAD

**Issue by ANTEVETY** [aws/lumberyard#403]
**Remove from your bootloader the mandatory installation of the VS 2015 redist(x64). I can not get rid of the error 0x80070666 simply by removing the previous versions, there are many tails left in the registry and they can not be found either automatically or manually.**

Any version

game designer

**Comment by Aristo7** [comment]
Thanks for reporting the issue. I've open an internal ticket to track this: LY-97434

Could you provide more details to the registry and bootloader you are referring to?

Thanks!

**Comment by ANTEVETY** [comment]
@Aristo7 This is the same problem [https://gamedev.amazon.com/forums/questions/61806/lumberyard-install-error-0x80070666.html](url) , but in my case, deleting previous versions of VS redist 2015-2017, and even everyone else, does not solve the problem. As said above, I do not find in the registry the remains for which your installer(LumberyardInstaller1.18.0.0.exe, and previous) clings and knocks an error. This is probably the only cases, but there is no desire to change and reinstall the windows) It would not be bad for your installer to simply install the engine and not crash with an error and install the end. (or put a checkmark to put something extra or not, in the end I myself can install it later) Yes, and why exactly 2015 your installer tries to install, doesn’t 2017 completely replace the ego?...                                            
    And a little off topic ... I am now on the unreal, but it is interesting for me to follow your development, and I have always been fascinated by the render of the Cryengine, but I always hated their "convenience of tools." Lumberyard I think the golden mean, and it would be nice to see in the future the same increase in rendering optimization (almost doubled fps) as happened with Crytek comparing version 3.8 => 5.5. example: [https://www.youtube.com/watch?v=dMdNg7lTkgQ&t=](url)  Thanks!

**Comment by AMZN-alexpete** [comment]
Closing this due to age of the topic and Visual Studio 2015 is no longer a supported version. If you are still experiencing this issue in the latest version of Lumberyard, please open a new Issue thanks!
