### ISSUE TITLE
autoexec.cfg doesn't work in release builds

### ISSUE THREAD

**Issue by wcbx** [aws/lumberyard#429]
**Describe the bug**
autoexec.cfg doesn't work in release builds

**Steps to reproduce**
Create a new project with autoexec.cfg to load a level and it won't work in release build.

**Lumberyard version**
1.21.0.

https://forums.awsgametech.com/t/loading-a-level-on-start/986/4

The problem is the gem which it recommends to use is now deprecated and we shouldn't have to hack the engine to get this to work.

Pretty trivial issue but I felt it should be given some attention.

**Comment by sourjon** [comment]
@wcbx , thanks for the info!  We'll take a look!  You can also post issues like this directly on the forums.

**Comment by wcbx** [comment]
This issue still hasn't been fixed for 1.22.0

**Comment by wcbx** [comment]
This issue still hasn't been fixed for 1.28

**Comment by wcbx** [comment]
https://forums.awsgametech.com/t/what-is-the-intended-way-for-a-release-build-of-a-game-to-start/4373/34?u=bloop

**Comment by wcbx** [comment]
I realize that autoexec.cfg is not intended for release builds but there should be an option to more easily auto load maps for release builds.

**Comment by wcbx** [comment]
So I'm closing this issue.
