### ISSUE TITLE
Unable to start a New project 

### ISSUE THREAD

**Issue by ssantosh2k** [aws/lumberyard#441]
Unable to create a project , with error at the Configure Project stage. Log says WindowsError: [Error 3] The system cannot find the path specified: 'C:/Amazon/sdk-tools-windows-4333796\\platforms/*.*'
Process failed with return code: 1

I think the double \\ is added by mistake. Where do I go and change the directory path.
![image](https://user-images.githubusercontent.com/45540657/68474449-6e9ff180-024b-11ea-91d5-bd66ddabfae1.png)

![image](https://user-images.githubusercontent.com/45540657/68474473-78295980-024b-11ea-807a-069da45eadba.png)

![image](https://user-images.githubusercontent.com/45540657/68474477-7eb7d100-024b-11ea-95de-9af6b7b18d30.png)

**Comment by AMZN-alexpete** [comment]
Hi @ssantosh2k, this actually looks like waf auto-detected Android SDK/NDK on your machine and then ran into an issue when it tried to enable Android support.

**Comment by wcbx** [comment]
It seems to me there should be some sort of user feedback on what is happening in the project configurator when a project is building. lmbr_waf provides feedback in terminal on how much has been built so far but the project configurator hides the command prompt for apparently for no good reason.

**Comment by AMZN-alexpete** [comment]
Closing due to no response from submitter.
