### ISSUE TITLE
Compile the game code needs dependencies from Engine and tools to compile

### ISSUE THREAD

**Issue by researchdeveloping** [aws/lumberyard#471]
**Describe the bug**
When you create a new project and want to configure it by "waf configure" and then compile it there will be some needed dependencies as Qt libraries to compile it - so it will fail. So the only way to configure and compile a new project is to configure it with Editor tools dependencies via for e.g.  Setup Assistant which make longer compilation time. 

**Steps to reproduce**
1. Create new empty project.
2. Select only "Compile the game code" in Setup Assistant (and two option to run project and editor).
3. lmbr_waf configure
4. lmbr_waf build_win_x64_vs2017_profile -p game

**Expected behavior**
Successful create VS solution and compile the project with minimal dependencies..

**Screenshots/Logs**
```
Build failed
<++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++>
Compilation failed - File: 'AutoCustomWindowDecorations.cpp.9426794.obj', Module: 'AzQtComponents', Configuration: 'win_x64_vs2017|profile', error code 2
    Input Files:   'i:\Amazon\lumberyard\dev\Code\Framework\AzQtComponents\AzQtComponents\Components\AutoCustomWindowDecorations.cpp'
    Output Files:      'i:\Amazon\lumberyard\dev\BinTemp\win_x64_vs2017_profile\Code\Framework\AzQtComponents\AzQtComponents\Components\AutoCustomWindowDecorations.cpp.9426794.obj'
        Output:
                AutoCustomWindowDecorations.cpp
i:\Amazon\lumberyard\dev\Code\Framework\AzQtComponents\AzQtComponents/Components/AutoCustomWindowDecorations.h
                i:\Amazon\lumberyard\dev\Code\Framework\AzQtComponents\AzQtComponents/Components/AutoCustomWindowDecorations.h(13): fatal error C1083: 'QObject': No such file or directory
```

**Lumberyard version**
1.23.1

**Comment by AMZN-alexpete** [comment]
Hi @researchdeveloping , we've created an internal issue LY-112659 to track this and are looking into it.
