### ISSUE TITLE
Cannot compile Android project via Android Studio

### ISSUE THREAD

**Issue by researchdeveloping** [aws/lumberyard#474]
**Describe the bug**
I cannot compile Android Project via Android Studio because WAF not generated CMakeLists.txt for PROJECT_NAMELuncher project in dev/Solutions/LumberyardAndroidSDK/PROJECT_NAMELuncher/ folder.

**Steps to reproduce**
1. lmbr_waf.bat configure,
2. Import LumberyardAndroidSDK project into Android Studio,
3. Sync project with gradle files / make project

**Expected behavior**
PROJECT_NAMELuncher should contain CMakeLists.txt (pre or generated).

**Screenshots/Logs**
```
CMake Error at CMakeLists.txt:61 (add_subdirectory):
The source directory
I:/Amazon/lumberyard/dev/Solutions/LumberyardAndroidSDK/TestProjectLauncher
does not contain a CMakeLists.txt file.
* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
* Get more help at https://help.gradle.org
BUILD FAILED in 1s
52 actionable tasks: 1 executed, 51 up-to-date
```

**Lumberyard version**
1.23.1 with fix described in issue 472.

**Comment by AMZN-alexpete** [comment]
Hi @researchdeveloping, we're having trouble reproducing this one.  Can you provide additional information from the configure output? LY-112661

**Comment by researchdeveloping** [comment]
Hi @AMZN-alexpete of course I will try to reproduce it with new project and then I will pass you all required logs. But what I can suggest to please verify if CMake project is generated corectly in dev\Solutions\LumberyardAndroidSDK\ folder. As I remember CMakeLists.txt in root contains "add_subdirectory(PROJECT_NAMELuncher)" so in this subfolder should be CMakeLists.txt file as is in others (for e.g. TestProject it will be TestProjectLuncher folder as a sibling TestProject, AzCore etc folders) - because as I remember Android Studio build this project based on CMake configuration. I am sorry that I wrote as I remember because I don't use this project from a few days. Please check if this is a point and let me know.

**Comment by researchdeveloping** [comment]
> Hi @researchdeveloping, we're having trouble reproducing this one.  Can you provide additional information from the configure output? LY-112661

Hi @AMZN-alexpete I recreate a Android Solution and this time the CMakeLists.txt file was generated. So I close this issue.
