### ISSUE TITLE
Serialization Errors

### ISSUE THREAD

**Issue by codeNcoffee** [aws/lumberyard#480]
<02:15:03> [Error] (Serialize) - Programmer error:

Classes deriving from AZ::Component are not declaring their base class to SerializeContext.
This will cause unexpected behavior such as components shifting around, or duplicating themselves.
Affected components:

- EditorEntitySearchComponent {BD1E6D92-58D5-4364-A3CE-D9BE63C0D9C8}
- EditorComponentAPIComponent {AC1A53C9-25BE-47D8-B9B5-60199AC73C2B}
- PropertyTreeEditorComponent {8CE26D19-2469-4E8D-A806-AC63E276B72E}

Reflection code should look something like this:

serializeContext->Class<MyComponent, AZ::Component, ... (other base classes, if any) ...>()
Make sure the Reflect function is called for all base classes as well.

**Comment by AMZN-nggieber** [comment]
Thank you for informing us of this issue. We'll be looking into your pull requests you submitted.
