### ISSUE TITLE
Changing path for projects

### ISSUE THREAD

**Issue by CyberNoble** [aws/lumberyard#488]
Hello everebody!
**What is your question?**
How can i remove my project from engine directory to any other place?
For some reasons i need to choose different path for my project rather than keep using default path which are set in engine dir
**Which part of the engine are you asking about?**
Project configurator

**Which version of Lumberyard are you using?**
1.23.1.0

**Comment by AMZN-puvvadar** [comment]
Hi @CyberNoble,

Moving your project outside of the dev directory is unfortunately currently not supported. We're aware that this is something users would like to see though. Thanks for your feedback!
