### ISSUE TITLE
why not has AWSNativeSDK's source?

### ISSUE THREAD

**Issue by gituser1024** [aws/lumberyard#493]
**What is your question?**
Please ask your question here. 

**Which part of the engine are you asking about?**
Please indicate the component of the engine that your question relates to (e.g., Script Canvas, PhysX, Animation etc.).

**Which version of Lumberyard are you using?**
State the Lumberyard version that you're using (e.g., v1.14.0.1 or v1.15.0.0 etc.).

**[OPTIONAL] What is your role in game development?**
Are you a game designer, engineer, artist, producer, something else?

**[OPTIONAL] Tell us about your project or studio.**
Briefly tell us about your project or studio.

**Comment by petrocket** [comment]
Hi @gituser1024 , The AWSNativeSDK source can be found here:
https://github.com/aws/aws-sdk-cpp

**Comment by gituser1024** [comment]
aws-sdk-cpp-1.7.341 has not aws-cpp-sdk-identity-management
but lumberyard run depend on it.
now aws-cpp-sdk-identity-management has been added to aws-sdk-cpp.
