### ISSUE TITLE
Where should I tell setup assistant to look for speedtree

### ISSUE THREAD

**Issue by AverageComet250** [aws/lumberyard#498]
I install speedtree in a different location from the default and know I don't know where to tell the setup assistant to look for it. Can anyone tell me. when changing the path, all I did was change 'C:\Program Files' to 'E:'.

**Comment by AMZN-Gene** [comment]
Good question!  I'll do some digging and see what I can find :)

**Comment by AverageComet250** [comment]
thanks

**Comment by AMZN-Gene** [comment]
There's a option to select SpeedTree's location at the very bottom of the Install Software section, let me know if this helps :)
![image](https://user-images.githubusercontent.com/32776221/86054121-6f6dd980-ba0e-11ea-8e4b-489b57108d9d.png)

**Comment by AverageComet250** [comment]
I already knew about that, but what folder should I browse too, as it asks you to browse to a folder. Which folder would this be as it doesn't tell you where to point it too in the Speedtree Installation directory.

**Comment by joshbeacham** [comment]
Select the directory that contains "SpeedTree Modeler Lumberyard.exe".

If the path is "E:\SpeedTree\SpeedTree for Lumberyard v8.0.0\win64\SpeedTree Modeler Lumberyard.exe" then you will navigate to "E:\SpeedTree\SpeedTree for Lumberyard v8.0.0\win64\".

**Comment by AverageComet250** [comment]
Thanks. I'll close this now.
