### ISSUE TITLE
how to generate SamplesProject's project file?

### ISSUE THREAD

**Issue by gituser1024** [aws/lumberyard#510]
lumberyard is good.
i found no Bin64vc141\LuaCompiler.exe  project file ?

**Comment by AMZN-Gene** [comment]
Hi!  I'm not sure what you're looking for... are you looking to generate SampleProject launcher, or Lua?

**Comment by AMZN-Gene** [comment]
LuaCompiler.exe should be downloaded after running git_bootstrap.exe
Have you ran git_bootstrap?

**Comment by gituser1024** [comment]
i found both SamplesProject and LuaCompiler.exe  's  project files.
i ran git_bootstrap and i have StarterGame launcher.
