### ISSUE TITLE
Incredibly slow installation

### ISSUE THREAD

**Issue by TushieSushi** [aws/lumberyard#543]
![image](https://user-images.githubusercontent.com/66031501/108603555-f100e600-73a8-11eb-8549-b362e5932cf7.png)
Its been almost 4 hours of download and installation, and its not even close to being done
The issue is not my internet, I got 100 MPBS download speed, Unreal engine takes 40 minutes to install and its 30+ GB

**Comment by AMZN-alexpete** [comment]
Hi @TushieSushi , sorry to hear the install is going slow. 1.27 was one of our larger releases and downloading + extracting the content can take some time.  Thank you for your feedback

**Comment by AMZN-alexpete** [comment]
Hi @TushieSushi , I heard you resolved the issue and wanted to post the solution here - ISP was throttling the traffic based on MIME type and switching to a VPN resolved the issue
