### ISSUE TITLE
Unable to build a new project

### ISSUE THREAD

**Issue by guifrediani** [aws/lumberyard#549]
**Describe the bug**
Cant build new project

**Steps to reproduce**
Create the new project using the Project Configurator using the default settings (v1.28.0.0)
Try to build it using the rebuild project button in Project Configurator (v1.28.0.0)

**Expected behavior**
Get a complete build to start a new project

**Screenshots/Logs**
https://www.dropbox.com/s/jdexl0pjje0ux3q/BuildTestlog.txt?dl=0 (download the log file)
**Lumberyard version**
v1.28.0.0 but i had the same issue with 1.27

**[OPTIONAL] What is your role in game development?**
Student

**[OPTIONAL] Tell us about your project or studio.**

**Comment by AMZN-alexpete** [comment]
Hi @guifrediani the logs indicate there is some permissions issue with your g:\lumberyard\1.28.0.0\dev\bin64vc142 folder. 

> Unable to copy g:\lumberyard\1.28.0.0\3rdparty\qt\5.15.1.1-az\msvc2019_64\bin\qt5core.dll to g:\lumberyard\1.28.0.0\dev\bin64vc142\qt5core.dll: [Errno 13] Permission denied: 'g:\\lumberyard\\1.28.0.0\\dev\\bin64vc142\\qt5core.dll'

 Is it possible you are using Perforce and have checked in the files in that folder, making them read only?  Another possibility is that those files are in use because the AssetProcessor or Editor is still open and need to be closed.

The other errors appear to be related to Qt and could indicate you are using a version of the Visual Studio compiler

> 		G:\Lumberyard\1.28.0.0\3rdParty\Qt\5.15.1.1-az\msvc2019_64\include\QtCore/qprocessordetection.h
> 		G:\Lumberyard\1.28.0.0\3rdParty\Qt\5.15.1.1-az\msvc2019_64\include\QtGui\qcolor.h(233): error C2220
> 		G:\Lumberyard\1.28.0.0\3rdParty\Qt\5.15.1.1-az\msvc2019_64\include\QtGui\qcolor.h(233): warning C5240: 'nodiscard': attribute is ignored in this syntactic position

**Comment by guifrediani** [comment]
Hey, i double checked and i dont have Perforce installed ( i didnt even know what Perforce was) and no other softwares were running while building, just the project configurator.

I installed Visual Studio using the Custom Install option and all the required SDKs, also, i dont know if i'm using the Visual Studio Compiler or not.

**Comment by AMZN-alexpete** [comment]
Hi @guifrediani , please investigate the permission issues writing to this folder g:\lumberyard\1.28.0.0\dev\bin64vc142

1. Does the folder have Administrator permissions only or readonly permissions?
2. Can you manually delete the g:\lumberyard\1.28.0.0\dev\bin64vc142\qt5core.dll file in Windows explorer?
3. Can you manually delete the g:\lumberyard\1.28.0.0\dev\bin64vc142\qt5core.dll file in Windows explorer with Asset Processor, Editor, ProjectConfigurator and SetupAssistant closed?
4. Is your computer controlled by your school or company? Sometimes these computers have extra rules enforced in Windows.

**Comment by guifrediani** [comment]
Hey
I checked and the folder had readonly checked, should i uncheck it? 
And yeah, i can manually delete the file in both situations, should i delete it?
And answering your final question, no, my computer is not controlled by any company or school.

**Comment by AMZN-alexpete** [comment]
Hi @guifrediani, I recommend unchecking the readonly setting for that folder and letting it unset readonly on all those files, and then trying to create the project again.  You shouldn't need to delete those files manually.

**Comment by guifrediani** [comment]
For some reason even after i uncheck the readonly setting, when i open the folder's settings, the readonly setting appears to be checked

**Comment by AMZN-alexpete** [comment]
Are the files themselves still set to readonly?

**Comment by guifrediani** [comment]
Yeah, even after i click apply to all folders and wait for it to finish

**Comment by AMZN-alexpete** [comment]
OK, if the files are no longer that should be good enough.  Please try creating the project again and see if you get the same or different errors.

**Comment by guifrediani** [comment]
I created a new project and tried to build, but i think i got the same errors: 

Link for logs download: https://www.dropbox.com/s/lmi6lakul96ldb0/SecondProject_build.log?dl=0

**Comment by AMZN-alexpete** [comment]
I've found another potential problem.  I think the version of Visual Studio 2019 you are using 14.28.29910 is lower than the minimum supported version [Visual Studio 2019 (any Edition): version 16.2.4](https://docs.aws.amazon.com/lumberyard/latest/releasenotes/lumberyard-v1.28.html)  Can you verify your Visual Studio 2019 version meets the minimum requirements?

**Comment by guifrediani** [comment]
Just checked, my VS version is 16.9.6, i guess it meets the minimum version right? I downloaded it today and checked the C++ game and desktop development, the windows 10 skd and the msvc version

**Comment by AMZN-alexpete** [comment]
That looks good,  can you open this file and search for the text 'nodiscard' without the quotes?  G:\Lumberyard\1.28.0.0\3rdParty\Qt\5.15.1.1-az\msvc2019_64\include\QtGui\qcolor.h

For some reason, the errors indicate this attribute exists in that file (and another) but I do not see that attribute in the official code.

		G:\Lumberyard\1.28.0.0\3rdParty\Qt\5.15.1.1-az\msvc2019_64\include\QtGui\qcolor.h(233): error C2220: o aviso a seguir  tratado como um erro
		**G:\Lumberyard\1.28.0.0\3rdParty\Qt\5.15.1.1-az\msvc2019_64\include\QtGui\qcolor.h(233): warning C5240: 'nodiscard': attribute is ignored in this syntactic position**
		G:\Lumberyard\1.28.0.0\3rdParty\Qt\5.15.1.1-az\msvc2019_64\include\QtGui\qcolor.h(233): note: para simplificar a migrao, considere o uso temporrio do sinalizador /Wv:18 com a verso do compilador com o qual voc compilava sem avisos
		**G:\Lumberyard\1.28.0.0\3rdParty\Qt\5.15.1.1-az\msvc2019_64\include\QtGui\qcolor.h(235): warning C5240: 'nodiscard': attribute is ignored in this syntactic position**
		G:\Lumberyard\1.28.0.0\3rdParty\Qt\5.15.1.1-az\msvc2019_64\include\QtGui\qcolor.h(235): note: para simplificar a migrao, considere o uso temporrio do sinalizador /Wv:18 com a verso do compilador com o qual voc compilava sem avisos

**Comment by guifrediani** [comment]
There is no 'nodiscard' in my files as well 

![nodiscard](https://user-images.githubusercontent.com/30310351/119396162-e5280700-bcaa-11eb-8007-028b18ba20da.png)

**Comment by AMZN-alexpete** [comment]
There is a possible related Qt bug filed here that may be related https://bugreports.qt.io/browse/QTBUG-93748

To test this theory can you try changing the code in qcolor.h from
```
#if QT_DEPRECATED_SINCE(5, 13)
    QT_DEPRECATED_X("Use QColor::lighter() instead")
    Q_REQUIRED_RESULT QColor light(int f = 150) const noexcept;
    QT_DEPRECATED_X("Use QColor::darker() instead")
    Q_REQUIRED_RESULT QColor dark(int f = 200) const noexcept;
#endif
```

to 
```
#if QT_DEPRECATED_SINCE(5, 13)
    Q_REQUIRED_RESULT  QT_DEPRECATED_X("Use QColor::lighter() instead")
    QColor light(int f = 150) const noexcept;
    Q_REQUIRED_RESULT QT_DEPRECATED_X("Use QColor::darker() instead")
    QColor dark(int f = 200) const noexcept;
#endif
```

then save and try to create a project again?  There may be a couple other places we need to change too to fix this issue (looking now)

**Comment by AMZN-alexpete** [comment]
Found another in 3rdParty\Qt\5.15.1.1-az\msvc2019_64\include\QtGui\qpainterpath.h, need to change from

```
#if QT_DEPRECATED_SINCE(5, 13)
    QT_DEPRECATED_X("Use r.subtracted() instead")
    Q_REQUIRED_RESULT QPainterPath subtractedInverted(const QPainterPath &r) const;
#endif
```

to 

```
#if QT_DEPRECATED_SINCE(5, 13)
    Q_REQUIRED_RESULT QT_DEPRECATED_X("Use r.subtracted() instead")
    QPainterPath subtractedInverted(const QPainterPath &r) const;
#endif
```

**Comment by guifrediani** [comment]
i just need to replace the content of those lines and then try to build the project again, right?

**Comment by AMZN-alexpete** [comment]
> i just need to replace the content of those lines and then try to build the project again, right?

correct

**Comment by guifrediani** [comment]
> > i just need to replace the content of those lines and then try to build the project again, right?
> 
> correct

lines replaced, rebuilding it now

**Comment by guifrediani** [comment]
> > > i just need to replace the content of those lines and then try to build the project again, right?
> > 
> > 
> > correct
> 
> lines replaced, rebuilding it now

no erros so far, but there are more than 5000 tasks to build so it might take a while to finish

**Comment by guifrediani** [comment]
More than 3000 tasks built and no errors so far, hopefully it stays that way and i can finally keep up with the official Lumberyard Tutorial

If anything happens, i'll let you know.

**Comment by guifrediani** [comment]
Good morning @AMZN-alexpete, i was able to build the new project and the welcomeguide project from youtube yesterday, thank you so much for helping me out on this! I still think that the fact that you were able to find the bug in another forum and basically, another subject is kinda crazy and impressive! Again, thank you so much and i hope that this issue can help other with the same bug! Have a nice day!

**Comment by AMZN-alexpete** [comment]
Thanks for reporting the issue, happy game-deving!
